### ISSUE TITLE
Assertionerror

### ISSUE THREAD

**Issue by Nielssss99** [polyvertex/fitdecode#20]
Hey 

During the use of the fitdecode module I encountered the following AssertionError:

  Traceback (most recent call last):
    File "C:\Users\niels\OneDrive\Documenten\Metec\Metec_python\unpack_fit_niels.py", line 35, in <module>
      for frame in fit_file:
    File "C:\Python\Python39\lib\site-packages\fitdecode\reader.py", line 232, in __iter__
      yield from self._read_next()
    File "C:\Python\Python39\lib\site-packages\fitdecode\reader.py", line 369, in _read_next
      assert self._chunk_size <= self._body_bytes_left
  AssertionError

The _chunk_size is 14 and _body_bytes_left is 12.

What's happening here and what's the best way to solve the problem? Ignoring the AssertionError seems to work, but I am not completely sure whether this is desirable at all.

Niels

**Comment by polyvertex** [comment]
Thanks for reporting this!

Would you mind providing the .FIT file (here or PM)? It could help.

**Comment by Nielssss99** [comment]
> Thanks for reporting this!
> 
> Would you mind providing the .FIT file (here or PM)? It could help.

**Comment by Nielssss99** [comment]
Github seems not to support .fit files, can I mail them to you?

**Comment by HaleTom** [comment]
@Nielssss99 what about you upload to your google drive and share from there?

Or https://ufile.io/
